app/events/forms.py
from idlelib.configdialog import is_int

import wtforms
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, DateField, IntegerField, FloatField, ValidationError, \
    FileField, TimeField
from wtforms.validators import DataRequired, Regexp, ValidationError
from datetime import date, datetime


class EventForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()], render_kw={'placeholder':'Title'})
    date = DateField('Date', validators=[DataRequired()], render_kw={'placeholder':'Date'})
    location = TextAreaField('Location', validators=[DataRequired()], render_kw={'placeholder':'Location'})
    content = TextAreaField('Content', validators=[DataRequired()], render_kw={'placeholder':'Description'})
    price = FloatField('Price', render_kw={'placeholder':'Price'})
    equipment = TextAreaField('Equipment Required', render_kw={'placeholder':'Equipment needed'})
    min_users= IntegerField ('Min Partecipant', render_kw={'placeholder':'Min partecipants'})
    weaknesses = TextAreaField('Weaknesses', render_kw={'placeholder':'Weaknesses'})
    picture1 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    picture2 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    picture3 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    submit = SubmitField('Create')

    def validate_date(self, date):
        if date.data<datetime.today().date():
            raise ValidationError('Date should be grater than today')

class ModifyEventForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()], render_kw={'placeholder':'New title'})
    date = DateField('Date', validators=[DataRequired()], render_kw={'placeholder':'New date'})
    location = TextAreaField('Location', validators=[DataRequired()], render_kw={'placeholder':'New location'})
    content = TextAreaField('Content', validators=[DataRequired()], render_kw={'placeholder':'New description'})
    price = FloatField('Price', render_kw={'placeholder':'New price'})
    equipment = TextAreaField('Equipment Required',render_kw={'placeholder':'Equipment'})
    min_users = IntegerField('Min Partecipant', render_kw={'placeholder':'Min partecipants'})
    weaknesses = TextAreaField('Weaknesses', render_kw={'placeholder':'Weaknesses'})
    picture1 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    picture2 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    picture3 = FileField('Update Event Image', validators=[FileAllowed(['jpeg', 'png', 'jpg'])])
    submit = SubmitField('Update')

    def validate_date(self, date):
        if date.data<datetime.today().date():
            raise ValidationError('Date should be grater than today')

class JoinEventForm(FlaskForm):
    yourcar = SubmitField('Go')
    someonescar = SubmitField('Go')
    bus = SubmitField('Go')
    yourown = SubmitField('Go')

class UseYourCarForm(FlaskForm):
    time_hour = IntegerField('Time of meeting',validators=[DataRequired()], render_kw={'placeholder':'Hour'})
    time_minute = IntegerField('Time of meeting', validators=[DataRequired()], render_kw={'placeholder': 'Minute'})
    place = StringField('Place of the meeting',validators=[DataRequired()], render_kw={'placeholder':'Place'})
    number_of_seats = IntegerField('Number of seats', validators=[DataRequired()], render_kw={'placeholder':'Number of seats'})
    submit = SubmitField('Ready?')

    def validate_number_of_seats(self, number_of_seats):
        if number_of_seats.data > 7 or number_of_seats.data < 0:
            raise ValidationError('The number of seats must be between 0 and 7')

    def validate_time_hour(self, time_hour):
        if time_hour.data > 23 or time_hour.data < 0:
            raise ValidationError('You have to insert the time in the 24h standard')

    def validate_time_minute(self, time_minute):
        if time_minute.data > 59 or time_minute.data < 0:
            raise ValidationError('You have to insert the time in the 24h standard')

    def validate_place(self, place):
        s = place.data.lower()
        s = place.data.strip()
        s = s.split()
        info = len(s)
        if (s[0] != 'corso' and s[0] != 'piazza' and s[0] != 'via' and s[0] != 'viale'):
            raise ValidationError('You must insert a correct address')
        if is_int(s[info - 1]) != True:
            raise ValidationError('You must insert a correct address')

app/events/__init__.py
from flask import Blueprint

events = Blueprint('events', __name__) #passo il nome della mia blueprint

from app.events import routes

app/events/routes.py
from flask import render_template, url_for, flash, redirect, request, abort
from sqlalchemy import null

from app import db
from app.events.forms import EventForm, JoinEventForm, ModifyEventForm, UseYourCarForm
from app.events.utils import save_picture
from models import Event, JoinEvent, User
from flask_login import current_user, login_required
from app.events import events
from datetime import date, time, datetime
from PIL import Image

@events.route("/event/new", methods=['GET', 'POST'])
@login_required
def new_event():
    form = EventForm()
    if form.validate_on_submit():
        if form.picture1.data and form.picture2.data==null and form.picture3.data==null:
            picture1 = save_picture(form.picture1.data)
            event = Event(title=form.title.data, date_event=form.date.data,
                      location = form.location.data, price = form.price.data, equipment = form.equipment.data,
                      min_users = form.min_users.data, content=form.content.data, weaknesses = form.weaknesses.data,
                      creator=current_user, image_event1 = picture1)
            db.session.add(event)
            db.session.commit()
            flash('event created', 'success')
            return redirect(url_for('main.home'))
        elif form.picture1.data and form.picture2.data and form.picture3.data==null:
            picture1 = save_picture(form.picture1.data)
            picture2 = save_picture(form.picture2.data)
            event = Event(title=form.title.data, date_event=form.date.data,
                      location = form.location.data, price = form.price.data, equipment = form.equipment.data,
                      min_users = form.min_users.data, content=form.content.data, weaknesses = form.weaknesses.data,
                      creator=current_user, image_event1 = picture1, image_event2 = picture2)
            db.session.add(event)
            db.session.commit()
            flash('event created', 'success')
            return redirect(url_for('main.home'))
        elif form.picture1.data and form.picture2.data and form.picture3.data:
            picture1 = save_picture(form.picture1.data)
            picture2 = save_picture(form.picture2.data)
            picture3 = save_picture(form.picture2.data)
            event = Event(title=form.title.data, date_event=form.date.data,
                      location = form.location.data, price = form.price.data, equipment = form.equipment.data,
                      min_users = form.min_users.data, content=form.content.data, weaknesses = form.weaknesses.data,
                      creator=current_user, image_event1 = picture1, image_event2 = picture2, image_event3 = picture3)
            db.session.add(event)
            db.session.commit()
            flash('event created', 'success')
            return redirect(url_for('main.home'))
        else:
            event = Event(title=form.title.data, date_event=form.date.data,
                          location=form.location.data, price=form.price.data, equipment=form.equipment.data,
                          min_users=form.min_users.data, content=form.content.data, weaknesses=form.weaknesses.data,
                          creator=current_user)
            db.session.add(event)
            db.session.commit()
            flash('event created', 'success')
            return redirect(url_for('main.home'))
    return render_template('create_event.html', title='New Event', form=form, legend='New Event')

@events.route("/event/<int:event_id>", methods=['GET', 'POST'])
def event(event_id):
    event = Event.query.get_or_404(event_id)
    return render_template('event.html', title='Event', event=event)

@events.route("/event/<int:event_id>/delete", methods=['POST'])
@login_required
def delete_event(event_id):
    event = Event.query.get_or_404(event_id)
    if event.creator != current_user:
        abort(403)
    db.session.delete(event)
    db.session.commit()
    flash('Your event has been deleted!', 'success')
    return redirect(url_for('main.home'))

@events.route("/event/<int:event_id>/update", methods=['GET', 'POST'])
@login_required
def update_event(event_id):
    event = Event.query.get_or_404(event_id)
    if event.creator!=current_user:
        abort(403) #risposta  per forbidden route
    form = ModifyEventForm()
    if form.validate_on_submit():
        if form.picture1.data:
            picture_file1 = save_picture(form.picture1.data)
            event.image_event1 = picture_file1
        if form.picture2.data:
            picture_file2 = save_picture(form.picture2.data)
            event.image_event2 = picture_file2
        if form.picture3.data:
            picture_file3 = save_picture(form.picture3.data)
            event.image_event3 = picture_file3
        event.title=form.title.data
        event.content=form.content.data
        event.date_event = form.date.data
        event.location = form.location.data
        event.price = form.price.data
        event.equipment = form.equipment.data
        event.min_users = form.min_users.data
        event.weaknesses = form.weaknesses.data
        db.session.commit()
        flash('update done', 'success')
        return redirect(url_for('users.events_created', event_id=event_id))
    elif request.method=='GET':
        form.title.data = event.title
        form.content.data = event.content
        form.date.data = event.date_event
        form.location.data = event.location
        form.price.data = event.price
        form.equipment.data = event.equipment
        form.min_users.data = event.min_users
        form.weaknesses.data = event.weaknesses
    form.title.data=event.title
    form.content.data=event.content
    form.date.data = event.date_event
    form.location.data = event.location
    form.price.data = event.price
    form.equipment.data = event.equipment
    form.min_users.data = event.min_users
    form.weaknesses.data = event.weaknesses
    image_event = url_for('static', filename='events_pics/' + event.image_event1)
    return render_template('modify_events.html', title='Update Event', form=form, legend='Update Event', image_event=image_event, event=event)

@events.route("/event/<int:event_id>/joinevent", methods=['GET', 'POST'])
@login_required
def join_event(event_id):
    user= current_user
    user_id = user.id
    form = JoinEventForm()
    event = Event.query.get_or_404(event_id)
    if event.date_event > datetime.today().date():
        if form.validate_on_submit():
            if form.someonescar.data:
                u = current_user.joined
                for e in u:
                    if e.event_id == event_id:
                        flash('You have already joined this event', 'danger')
                        return redirect(url_for('main.home'))
                join_event = JoinEvent(event_id=event_id, user_id=user_id, transport_type='someonescar', time_hour=0,
                                       time_minute=0, place='null', number_of_seats=0, user_id_car_joined = 0)
                db.session.add(join_event)
                db.session.commit()
                return redirect(url_for('events.someonescar_info', event_id=event_id, transport_type='someonescar'))
            elif form.yourcar.data:
                u = current_user.joined
                for e in u:
                    if e.event_id == event_id:
                        flash('You have already joined this event', 'danger')
                        return redirect(url_for('main.home'))
                return redirect(url_for('events.your_car_info', event_id=event_id, transport_type='yourcar'))
            elif form.bus.data:
                u = current_user.joined
                for e in u:
                    if e.event_id == event_id:
                        flash('You have already joined this event', 'danger')
                        return redirect(url_for('main.home'))
                join_event = JoinEvent(event_id=event_id, user_id=user_id, transport_type='bus', time_hour=0,
                                       time_minute=0, place='null', number_of_seats=0, user_id_car_joined = 0)
                db.session.add(join_event)
                db.session.commit()
                return redirect(url_for('events.event_joined', event_id=event_id, transport_type='bus'))
            elif form.yourown.data:
                u = current_user.joined
                for e in u:
                    if e.event_id == event_id:
                        flash('You have already joined this event', 'danger')
                        return redirect(url_for('main.home'))
                join_event = JoinEvent(event_id=event_id, user_id=user_id, transport_type='yourown', time_hour=0,
                                       time_minute=0, place='null', number_of_seats=0, user_id_car_joined = 0)
                db.session.add(join_event)
                db.session.commit()
                return redirect(url_for('events.event_joined', event_id=event_id, transport_type='yourown'))
    else:
        flash('You cannot join this event, it is expired', 'danger')
        return redirect(url_for('main.home'))
    return render_template('join_event.html', title='Join Event', legend='Join Event', form=form)

@events.route("/event/<int:event_id>/delete_event_joined", methods=['GET','POST'])
@login_required
def delete_event_joined(event_id):
    user = current_user
    u = current_user.joined
    for e in u:
        if e.event_id == event_id:
            if e.transport_type == 'someonescar' and e.user_id_car_joined!=0 :
                user_car = e.user_id_car_joined
                db.session.delete(e)
                db.session.commit()
                user2 = User.query.get_or_404(user_car)
                u2 = user2.joined
                for e2 in u2:
                    if e2.event_id == event_id:
                        e2.number_of_seats = e2.number_of_seats + 1
                        db.session.commit()

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__) #passo il nome della mia blueprint

from app.posts import routes

app/posts/routes.py
from datetime import datetime

from flask import render_template, url_for, flash, redirect, request, abort
from app import db
from app.posts.forms import PostForm
from models import Post, JoinEvent, Event
from flask_login import current_user, login_required
from app.posts import posts
from app.events import events
#from PIL import Image


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    jevents = JoinEvent.query.filter_by(user_id=current_user.id).all()
    events_already_done = []
    for e in jevents:
        ev = Event.query.filter_by(id=e.event_id).first()
        if ev:
            if ev.date_event < datetime.today().date():
                events_already_done.append(ev)
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('post created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post', events = events_already_done, ea_tot = len(events_already_done))

@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title='Post', post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403) #risposta per forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit() #sto solo aggiornando qualcosa che c'è già
        flash('update done', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method=='GET':
        form.title.data = post.title
        form.content.data = post.content
    form.title.data=post.title
    form.content.data=post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route("/reviews", methods=['GET', 'POST'])
def reviews():
    page = request.args.get('page', 1, type=int)  # possiamo passare il numero di post che vogliamo per pagina
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5) #richiamo tutti i post
    return render_template('comments.html', posts=posts)

app/templates/comments.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="row text-center justify-content-center mb-3">
            <div class="col-xl-6 col-lg-8 pt-4">
                <h2 class="font-weight-bold">Our customers reviews</h2>
                {%  if current_user.username != null %}
                    <p class="text-muted">Do you want to leave a review? <a href="{{ url_for('posts.new_post') }}">Write it now!</a></p>
                {% else %}
                    <p class="text-muted">A notice board full of reviews made by our loyal customers!</p>
                {% endif %}
            </div>
        </div>


            <div class="container pb-5 pt-3">
                <div class="row">
                    <div class="col-lg-6 offset-lg-3">
                        {% for post in posts.items %}
                        <div class="cardbox shadow-lg bg-white p-3">
                            <div class="cardbox-heading">
                                <div class="media m-0">
                                    <div class="d-flex m-1">
                                        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                                    </div>
                                    <div class="media-body">
                                        <a class="mr-2" href="">{{ post.author.username }}</a>
                                        <small><span><i class="icon ion-md-time"></i>{{ post.date_posted.strftime('%Y-%m-%d') }}</span></small>
                                    </div>
                                </div><!--/ media -->
                            </div><!--/ cardbox-heading -->
                            <div class="cardbox-item pr-4 pl-4 pb-4 pt-1">
                                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                                <p class="article-content">{{ post.content }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div><!--/ col-lg-3 -->
                </div><!--/ row -->
            </div><!--/ container -->


    </div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="/app/static/img/icon0.png">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'>



    {% if title %}
        <title>DinTOrni - {{ title }}</title>
    {% else %}
        <title>DinTOrni</title>
    {% endif %}
</head>
<body style="background-color: #E8E9EB;" >
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-light text-color:white fixed-top" style="background-color:#313638;">
        <div class="container">
          <a class="navbar-brand mr-4 text-white" href="/">
              <img style="max-width:50px;" src="{{ url_for('static', filename='img/' + 'icon_w.png') }}">
              <img style="max-width:150px;" src="{{ url_for('static', filename='img/' + 'nome_w_nobg.png') }}">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <!--<div class="navbar-nav mr-auto">
              <a class="nav-item nav-link text-white" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link text-white" href="{{ url_for('main.about') }}">About</a>
            </div>-->
            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-auto ms-auto">
                <a class="nav-item nav-link text-white" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link text-white" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-item nav-link text-white" href="{{ url_for('posts.reviews') }}">Reviews</a>

                {%  if current_user.is_authenticated %}
                        {%  if current_user.username != null %}
                            <a class="nav-item nav-link text-white" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link text-white" href="{{ url_for('users.user_events') }}">My events</a>
                        {%  else %}
                            <a class="nav-item nav-link text-white" href="{{ url_for('events.new_event') }}">New event</a>
                            <a class="nav-item nav-link text-white" href="{{ url_for('users.account_business') }}">Account</a>
                            <a class="nav-item nav-link text-white" href="{{ url_for('users.events_created') }}">My events</a>

                        {% endif %}
                {% endif %}

            {%  if current_user.is_authenticated %}
                <a class="nav-item nav-link text-white " href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
                 <a class="nav-item nav-link text-white" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link text-white"  href="{{ url_for('users.general') }}">Registration</a>
            {% endif %}


               </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container" >
      <div class="row">
        <div class="col-lg-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <!-- se il messaggio non è vuoto-->
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>


    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<footer class="text-center text-white" style="background-color: #F06543;">
  <!-- Grid container -->
  <div class="container p-4 pb-0" style="">
    <!-- Section: Form -->
    <section class="mt-2 mb-0 pt-2 pb-2">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex mt-1 pt-1 mb-0 justify-content-center" style="margin-top: 10px; margin-bottom: 10px">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example29" class="form-control" />
             <!-- <label class="form-label" for="form5Example29">Enter your email to discover new experiences around you!</label>-->
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    ©️ 2022 Copyright:
    <a class="text-white" href="{{ url_for('main.home') }}"> www.dinTOrni.it</a>
  </div>
  <!-- Copyright -->
</footer>
</body>


</html>

app/templates/no_car.html
{% extends "layout.html" %}
{% block content %}
    <div class="container login-container pb-5 mb-0" style="height: 800px">
        <div class="row justify-content-center pb-5" >
            <div class="col pr-0 pl-0 pb-5 login-form-1">
                <h3 class="pb-3">You will reach the event by car!</h3>
                    <div>
                        <p class="text-center font-weight-light">Congratulation, your choice is the most sustainable!</p>
                        <p class="text-center font-weight-light">We'll contact you by email when someone will share his/her car.</p>
                        <p class="text-center font-weight-light">See you there!</p>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

app/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <div class="container pb-5 pt-5 mt-2 mb-5">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 mb-5">
                <div class="cardbox shadow-lg bg-white p-3">
                    <div class="cardbox-heading">
                        <div class="media m-0">
                            <div class="d-flex m-1">
                                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                            </div>
                            <div class="media-body">
                                <a class="mr-2" href="">{{ post.author.username }}</a>
                                <small><span><i class="icon ion-md-time"></i>{{ post.date_posted.strftime('%Y-%m-%d') }}</span></small>
                            </div>
                        </div><!--/ media -->
                    </div><!--/ cardbox-heading -->
                    <div class="cardbox-item pr-4 pl-4 pb-4 pt-1">
                        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                        <p class="article-content">{{ post.content }}</p>
                    </div>
                    {% if post.author == current_user %}
                        <div class="container align-center pb-4">
                            <div class="row">
                            <div class="col-md-6 justify-content-start">
                                <form action="{{ url_for('posts.update_post', post_id=post.id) }}" method="POST">
                                    <input class="btnSubmit text-white" type="submit" style="background: #F06543" value="Update"> <!-- il btn-danger è per farlo rosso -->
                                </form>
                            </div>
                            <div class="col-md-6 justify-content-start">
                                <button class="btnSubmit text-white"  style="background: #F06543;" onclick="document.getElementById('id01').style.display='block'">Delete</button>
                            </div>
                                <div id="id01" class="modal align-center" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <span onclick="document.getElementById('id01').style.display='none'" class="close" style="color: #F06543" title="Close Modal">CLOSE</span>
                                    <form class="modal-content" action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                                        <div class="container p-5">
                                            <h1 class="justify-content-center align-center">Are you sure?</h1>
                                            <p>Your post will be no longer available for other users!
                                            </p>
                                            <div class="clearfix justify-content-center">
                                                <div class="row justify-content-center">
                                                    <div class="col-md-12 justify-content-start">
                                                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                                                            <input class="btnSubmit text-white" type="submit" style="background: #F06543" value="Delete"> <!-- il btn-danger è per farlo rosso -->
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    {% endif %}
                </div>
            </div><!--/ col-lg-3 -->
        </div><!--/ row -->
  </div><!--/ container -->



{% endblock content %}